version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: love_me_frontend
    ports:
      - "8081:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro

backend:
  build:
    context: ./backend
  container_name: love_me_backend
  ports:
    - "5000:5000"
  depends_on:
    - db

  db:
    image: mysql:latest
    container_name: website_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: client_data
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
