version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: love_me_frontend
    ports:
      - "8081:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro

  backend:
    build:
      context: ./backend
    container_name: love_me_backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: full-stack-project_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: client_data
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
